COUNTRY_NAME_CHOICES = (
    (u"AL", u"Albania"),
    (u"AM", u"Armenia"),
    (u"AZ", u"Azerbaijan"),
    (u"BZ", u"Belize"),
    (u"BJ", u"Benin"),
    (u"BW", u"Botswana"),
    (u"BG", u"Bulgaria"),
    (u"BF", u"Burkina Faso"),
    (u"KH", u"Cambodia"),
    (u"CM", u"Cameroon"),
    (u"CV", u"Cape Verde"),
    (u"CN", u"China"),
    (u"CO", u"Colombia"),
    (u"CR", u"Costa Rica"),
    (u"DO", u"Dominican Republic"),
    (u"LC", u"Eastern Caribbean"),
    (u"SV", u"El Salvador"),
    (u"EC", u"Ecuador"),
    (u"ET", u"Ethopia"),
    (u"FJ", u"Fiji"),
    (u"GE", u"Georgia"),
    (u"GH", u"Ghana"),
    (u"GT", u"Guatemala"),
    (u"GN", u"Guinea"),
    (u"GY", u"Guyana"),
    (u"HN", u"Honduras"),
    (u"ID", u"Indonesia"),
    (u"JM", u"Jamaica"),
    (u"JO", u"Jordan"),
    (u"KZ", u"Kazakhstan"),
    (u"KE", u"Kenya"),
    (u"KG", u"Kyrgyz Republic"),
    (u"LS", u"Lesoto"),
    (u"LR", u"Liberia"),
    (u"MK", u"Macedonia"),
    (u"MG", u"Madagascar"),
    (u"MW", u"Malawi"),
    (u"ML", u"Mali"),
    (u"MX", u"Mexico"),
    (u"FM", u"Micronesia and Polynesia"),
    (u"MD", u"Moldova"),
    (u"MN", u"Mongolia"),
    (u"MA", u"Morocco"),
    (u"MZ", u"Mozambique"),
    (u"NA", u"Namibia"),
    (u"NP", u"Nepal"),
    (u"NI", u"Nicaragua"),
    (u"NE", u"Niger"),
    (u"PA", u"Panama"),
    (u"PY", u"Paraguay"),
    (u"PE", u"Peru"),
    (u"PH", u"Philipines"),
    (u"RO", u"Romania"),
    (u"RW", u"Rwanda"),
    (u"WS", u"Samoa"),
    (u"SN", u"Senegal"),
    (u"SL", u"Sierra Leone"),
    (u"ZA", u"South Africa"),
    (u"SR", u"Suriname"),
    (u"SZ", u"Swaziland"),
    (u"TZ", u"Tanzania"),
    (u"GM", u"The Gambia"),
    (u"TH", u"Thailand"),
    (u"TG", u"Togo"),
    (u"TO", u"Tnoga"),
    (u"UG", u"Uganda"),
    (u"UA", u"Ukraine"),
    (u"VU", u"Vanatu"),
    (u"ZM", u"Zambia")
)

STATES = (
    (u"AL", u"Alabama"),
    (u"AK", u"Alaska"),
    (u"AZ", u"Arizona"),
    (u"AR", u"Arkansas"),
    (u"CA", u"California"),
    (u"CO", u"Colorado"),
    (u"CT", u"Connecticut"),
    (u"DE", u"Delaware"),
    (u"FL", u"Florida"),
    (u"GA", u"Georgia"),
    (u"HI", u"Hawaii"),
    (u"ID", u"Idaho"),
    (u"IL", u"Illinois"),
    (u"IN", u"Indiana"),
    (u"IA", u"Iowa"),
    (u"KS", u"Kansas"),
    (u"KY", u"Kentucky"),
    (u"LA", u"Louisiana"),
    (u"ME", u"Maine"),
    (u"MD", u"Maryland"),
    (u"MA", u"Massachusetts"),
    (u"MI", u"Michigan"),
    (u"MN", u"Minnesota"),
    (u"MS", u"Mississippi"),
    (u"MO", u"Missouri"),
    (u"MT", u"Montana"),
    (u"NE", u"Nebraska"),
    (u"NV", u"Nevada"),
    (u"NH", u"New Hampshire"),
    (u"NJ", u"New Jersey"),
    (u"NM", u"New Mexico"),
    (u"NY", u"New York"),
    (u"NC", u"North Carolina"),
    (u"ND", u"North Dakota"),
    (u"OH", u"Ohio"),
    (u"OK", u"Oklahoma"),
    (u"OR", u"Oregon"),
    (u"PA", u"Pennsylvania"),
    (u"RI", u"Rhode Island"),
    (u"SC", u"South Carolina"),
    (u"SD", u"South Dakota"),
    (u"TN", u"Tennessee"),
    (u"TX", u"Texas"),
    (u"UT", u"Utah"),
    (u"VT", u"Vermont"),
    (u"VA", u"Virginia"),
    (u"WA", u"Washington"),
    (u"WV", u"West Virginia"),
    (u"WI", u"Wisconsin"),
    (u"WY", u"Wyoming"),
    (u"AS", u"American Samoa"),
    (u"DC", u"District of Columbia"),
    (u"FM", u"Federated States of Micronesia"),
    (u"GU", u"Guam"),
    (u"MH", u"Marshall Islands"),
    (u"MP", u"Northern Mariana Islands"),
    (u"PW", u"Palau"),
    (u"PR", u"Puerto Rico"),
    (u"VI", u"Virgin Islands")
)

GRADES = (
    ("K", "Kindergarden"),
    ("1", "First grade"),
    ("2", "Second grade"),
    ("3", "Third grade"),
    ("4", "Fourth grade"),
    ("5", "Fifth grade"),
    ("6", "Sixth grade"),
    ("7", "Seventh grade"),
    ("8", "Eighth grade"),
    ("9", "Ninth grade"),
    ("10", "Tenth grade"),
    ("11", "Eleventh grade"),
    ("12", "Twelfth grade")
)
